// Regenerates the signed fixture that shou::enclave_tests verifies.
//
// Move cannot sign, so the on-chain acceptance path can only be tested
// against a signature produced out here. Running this prints a Move
// snippet to paste into tests/enclave_tests.move. If the BCS layouts in
// attestation.ts and enclave.move ever drift apart, that test fails —
// which is exactly the alarm we want.
//
//   npm run fixture --prefix shou/enclave

import { generateEnclaveKeypair, serializeAttestation, toHex } from './attestation.ts';

const FIXTURE = {
  timestampMs: 1_700_000_000_000,
  messageHash: new Uint8Array([0x00, 0x11, 0x22, 0x33]),
  policyId: '0x00000000000000000000000000000000000000000000000000000000000000cc',
  recipient: '0x00000000000000000000000000000000000000000000000000000000000000c1',
  amount: 1000n,
  riskTier: 2, // HIGH
  truthScore: 91,
};

const keypair = generateEnclaveKeypair();
const payload = serializeAttestation(FIXTURE);
const signature = keypair.sign(payload);

console.log(`// Generated by shou/enclave/src/sign-fixture.ts — do not hand-edit.
const ENCLAVE_PUBKEY: vector<u8> =
    x"${toHex(keypair.publicKeyRaw)}";
const FIXTURE_SIGNATURE: vector<u8> =
    x"${toHex(signature)}";
const FIXTURE_TIMESTAMP_MS: u64 = ${FIXTURE.timestampMs};
const FIXTURE_MESSAGE_HASH: vector<u8> = x"${toHex(FIXTURE.messageHash)}";
const FIXTURE_POLICY_ID: address = @${FIXTURE.policyId};
const FIXTURE_RECIPIENT: address = @${FIXTURE.recipient};
const FIXTURE_AMOUNT: u64 = ${FIXTURE.amount};
const FIXTURE_TIER: u8 = ${FIXTURE.riskTier};
const FIXTURE_TRUTH_SCORE: u8 = ${FIXTURE.truthScore};`);

console.error(`\nserialized payload (${payload.length} bytes): ${toHex(payload)}`);
